apiVersion: v2
name: nodereaper
description: A Kubernetes tool for automatically detecting and cleaning up empty nodes
type: application
version: 1.0.0
appVersion: "v1.0.0"
keywords:
  - kubernetes
  - node-management
  - cleanup
  - automation
home: https://github.com/sdaberdaku/nodereaper
sources:
  - https://github.com/sdaberdaku/nodereaper
maintainers:
  - name: Sebastian Daberdaku
    email: sdaberdaku@users.noreply.github.com
annotations:
  licenses: Apache-2.0
